#!/bin/bash

# Game Recharge Platform - Environment Variables Sync to Vercel (Preview)
# This script exports local environment variables to Vercel Preview environment

set -e

echo "🔧 Game Recharge Platform - Sync Environment Variables to Vercel Preview"
echo "=================================================================="

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI is not installed."
    echo "Please install it with: npm i -g vercel"
    exit 1
fi

# Check if .env.local exists
if [ ! -f ".env.local" ]; then
    echo "❌ .env.local file not found"
    exit 1
fi

echo "📖 Found .env.local file"

# Function to export environment variable
export_env_var() {
    local key=$1
    local value=$2
    local env_type="preview"

    echo "Exporting: $key"

    # Remove quotes from value
    value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')

    # Try to remove existing variable first, then add new one
    vercel env rm "$key" "$env_type" 2>/dev/null || true
    echo "$value" | vercel env add "$key" "$env_type"
}

echo ""
echo "🚀 Exporting environment variables to Vercel (Preview/Development)..."
echo "=================================================================="

# Read and export each variable
while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ $key =~ ^[[:space:]]*# ]] && continue
    [[ -z $key ]] && continue

    # Remove any surrounding quotes from key
    key=$(echo "$key" | xargs)

    # Only export variables in our whitelist
    case "$key" in
        NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE)
            export_env_var "$key" "$value"
            ;;
        *)
            echo "⚠️  Skipping: $key"
            ;;
    esac
done < <(grep -E '^[A-Z_]+=' .env.local)

echo "=================================================================="
echo "✅ Environment variables exported to Preview/Development"

# Create a reference file
filename=".vercel.env.preview"
cat > "$filename" << EOF
# Game Recharge Platform - Vercel Environment Variables (Preview/Development)
# Generated by sync-env-preview.sh
# Date: $(date)

EOF

# Add the environment variables to the reference file
while IFS='=' read -r key value; do
    [[ $key =~ ^[[:space:]]*# ]] && continue
    [[ -z $key ]] && continue

    key=$(echo "$key" | xargs)

    case "$key" in
        NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE)
        echo "$key=$value" >> "$filename"
        ;;
    esac
done < <(grep -E '^[A-Z_]+=' .env.local)

# Add important notes
cat >> "$filename" << EOF

# ⚠️  IMPORTANT MANUAL SETUP REQUIRED:
# 1. STRIPE_WEBHOOK_SECRET - Get from Stripe Dashboard > Developers > Webhooks
#    Endpoint URL: https://your-domain.vercel.app/api/webhooks/stripe
#    Events: checkout.session.completed, checkout.session.expired,
#            payment_intent.succeeded, payment_intent.payment_failed,
#            payment_intent.canceled

# 2. For Production Environment:
#    - Update NEXT_PUBLIC_APP_URL to: https://your-domain.vercel.app
#    - Update CORS_ORIGINS to: https://your-domain.vercel.app
#    - Run: pnpm sync-env:production (when ready)

# 3. Check your Vercel Dashboard:
#    https://vercel.com/dashboard
EOF

echo "📝 Created reference file: $filename"

echo ""
echo "🎉 Environment variables sync completed!"
echo ""
echo "📋 Next Steps:"
echo "1. ✅ Environment variables are now in Vercel Preview environment"
echo "2. ⚠️  Manually add STRIPE_WEBHOOK_SECRET (see $filename for instructions)"
echo "3. 🚀 Trigger a new deployment on Vercel or push to trigger auto-deploy"
echo "4. 🧪 Test your application at the deployed URL"
echo ""
echo "🔗 Vercel Dashboard: https://vercel.com/dashboard"