#!/bin/bash

# Game Recharge Platform - Environment Variables Sync to Vercel
# This script exports local environment variables to Vercel

set -e

echo "🔧 Game Recharge Platform - Environment Variables Sync Tool"
echo "=========================================================="

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI is not installed."
    echo "Please install it with: npm i -g vercel"
    exit 1
fi

# Check if .env.local exists
if [ ! -f ".env.local" ]; then
    echo "❌ .env.local file not found"
    exit 1
fi

echo "📖 Found .env.local file"

# Function to export environment variable
export_env_var() {
    local key=$1
    local value=$2
    local env_type=$3

    echo "Exporting: $key"

    # Remove quotes from value
    value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')

    # Try to remove existing variable first, then add new one
    vercel env rm "$key" "$env_type" 2>/dev/null || true
    echo "$value" | vercel env add "$key" "$env_type"
}

# Function to sync environment variables
sync_to_vercel() {
    local env_type=$1
    local env_name=$2

    echo ""
    echo "🚀 Exporting environment variables to Vercel ($env_name)..."
    echo "=========================================================="

    # Read and export each variable
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ $key =~ ^[[:space:]]*# ]] && continue
        [[ -z $key ]] && continue

        # Remove any surrounding quotes from key
        key=$(echo "$key" | xargs)

        # Only export variables in our whitelist
        case "$key" in
            NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE)
                export_env_var "$key" "$value" "$env_type"
                ;;
            *)
                echo "⚠️  Skipping: $key"
                ;;
        esac
    done < <(grep -E '^[A-Z_]+=' .env.local)

    echo "=========================================================="
    echo "✅ Environment variables exported to $env_name"
}

# Create a reference file
create_reference_file() {
    local env_type=$1
    local filename=".vercel.env.$env_type"

    # Set title based on environment type
    if [ "$env_type" = "production" ]; then
        local env_title="Production"
    else
        local env_title="Preview/Development"
    fi

    cat > "$filename" << EOF
# Game Recharge Platform - Vercel Environment Variables ($env_title)
# Generated by sync-env.sh
# Date: $(date)

EOF

    # Add the environment variables to the reference file
    while IFS='=' read -r key value; do
        [[ $key =~ ^[[:space:]]*# ]] && continue
        [[ -z $key ]] && continue

        key=$(echo "$key" | xargs)

        case "$key" in
            NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE)
                echo "$key=$value" >> "$filename"
                ;;
        esac
    done < <(grep -E '^[A-Z_]+=' .env.local)

    # Add important notes
    cat >> "$filename" << EOF

# ⚠️  IMPORTANT MANUAL SETUP REQUIRED:
# 1. STRIPE_WEBHOOK_SECRET - Get from Stripe Dashboard > Developers > Webhooks
#    Endpoint URL: https://your-domain.vercel.app/api/webhooks/stripe
#    Events: checkout.session.completed, checkout.session.expired,
#            payment_intent.succeeded, payment_intent.payment_failed,
#            payment_intent.canceled

# 2. Update NEXT_PUBLIC_APP_URL for production:
#    Should be: https://your-domain.vercel.app

# 3. Update CORS_ORIGINS for production:
#    Should be: https://your-domain.vercel.app
EOF

    echo "📝 Created reference file: $filename"
}

# Ask user for environment choice
echo ""
echo "🤔 Where do you want to export the environment variables?"
echo "1) Production"
echo "2) Preview/Development"
echo "3) Both"
echo -n "Choice [1-3]: "
read -r choice

case $choice in
    1)
        sync_to_vercel "production" "Production"
        create_reference_file "production"
        ;;
    2)
        sync_to_vercel "preview" "Preview/Development"
        create_reference_file "preview"
        ;;
    3)
        echo ""
        echo "🔄 Exporting to both environments..."
        sync_to_vercel "production" "Production"
        sync_to_vercel "preview" "Preview/Development"
        create_reference_file "production"
        create_reference_file "preview"
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "🎉 Environment variables sync completed!"
echo ""
echo "📋 Next Steps:"
echo "1. Check your Vercel Dashboard for the environment variables"
echo "2. Manually add STRIPE_WEBHOOK_SECRET (see .vercel.env file for instructions)"
echo "3. Trigger a new deployment on Vercel"
echo "4. Test your application at the deployed URL"
echo ""
echo "🔗 Vercel Dashboard: https://vercel.com/dashboard"