#!/bin/bash

# Game Recharge Platform - Environment Variables Sync to Vercel (Production)
# This script exports local environment variables to Vercel Production environment

set -e

echo "🚀 Game Recharge Platform - Deploy to Production Environment"
echo "============================================================="

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI is not installed."
    echo "Please install it with: npm i -g vercel"
    exit 1
fi

# Check if .env.local exists
if [ ! -f ".env.local" ]; then
    echo "❌ .env.local file not found"
    exit 1
fi

echo "📖 Found .env.local file"

# Function to export environment variable
export_env_var() {
    local key=$1
    local value=$2
    local env_type="production"

    echo "Exporting: $key"

    # Remove quotes from value
    value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')

    # Remove existing variable first, then add new one
    vercel env rm "$key" "$env_type" 2>/dev/null || true
    sleep 0.5  # Brief pause to ensure removal completes
    echo "$value" | vercel env add "$key" "$env_type"
}

echo ""
echo "🚀 Exporting environment variables to Vercel Production..."
echo "============================================================="

# Read and export each variable
while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ $key =~ ^[[:space:]]*# ]] && continue
    [[ -z $key ]] && continue

    # Remove any surrounding quotes from key
    key=$(echo "$key" | xargs)

    # Only export variables in our whitelist
    case "$key" in
        NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE|STRIPE_WEBHOOK_SECRET)
            export_env_var "$key" "$value"
            ;;
        *)
            echo "⚠️  Skipping: $key"
            ;;
    esac
done < <(grep -E '^[A-Z_]+=' .env.local)

echo "============================================================="
echo "✅ Environment variables exported to Production"

# Update production-specific values
echo ""
echo "🔧 Updating production-specific configuration..."

# Update NEXT_PUBLIC_APP_URL to production URL
echo "Updating NEXT_PUBLIC_APP_URL to https://recharge-steel.vercel.app"
vercel env rm NEXT_PUBLIC_APP_URL production 2>/dev/null || true
echo "https://recharge-steel.vercel.app" | vercel env add NEXT_PUBLIC_APP_URL production

# Update CORS_ORIGINS to production URL
echo "Updating CORS_ORIGINS to https://recharge-steel.vercel.app"
vercel env rm CORS_ORIGINS production 2>/dev/null || true
echo "https://recharge-steel.vercel.app" | vercel env add CORS_ORIGINS production

# Set NODE_ENV to production
echo "Setting NODE_ENV to production"
vercel env rm NODE_ENV production 2>/dev/null || true
echo "production" | vercel env add NODE_ENV production

echo "============================================================="
echo "✅ Production configuration updated"

# Create a reference file
filename=".vercel.env.production"
cat > "$filename" << EOF
# Game Recharge Platform - Vercel Environment Variables (Production)
# Generated by sync-env-production.sh
# Date: $(date)

EOF

# Add the environment variables to the reference file
while IFS='=' read -r key value; do
    [[ $key =~ ^[[:space:]]*# ]] && continue
    [[ -z $key ]] && continue

    key=$(echo "$key" | xargs)

    case "$key" in
        NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_POOLER_URL|NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY|STRIPE_SECRET_KEY|NEXT_PUBLIC_APP_URL|DEFAULT_LOCALE|SUPPORTED_LOCALES|NODE_ENV|JWT_SECRET|CORS_ORIGINS|RATE_LIMIT_PER_MINUTE|MAX_FILE_SIZE|STRIPE_WEBHOOK_SECRET)
        echo "$key=$value" >> "$filename"
        ;;
    esac
done < <(grep -E '^[A-Z_]+=' .env.local)

# Add production-specific notes
cat >> "$filename" << EOF

# ✅ PRODUCTION CONFIGURATION SET:
# - NEXT_PUBLIC_APP_URL: https://recharge-steel.vercel.app
# - CORS_ORIGINS: https://recharge-steel.vercel.app
# - NODE_ENV: production

# 🎉 Deployment Status:
# - All environment variables are configured
# - STRIPE_WEBHOOK_SECRET is included
# - Ready for production deployment

# 📋 Deployment Checklist:
# ✅ Environment variables configured
# ✅ Production URLs set
# ✅ CORS configured for production
# ⏳ Trigger production deployment
# ⏳ Test production functionality

# 🔗 Links:
# - Vercel Dashboard: https://vercel.com/dashboard
# - Production URL: https://recharge-steel.vercel.app
# - Stripe Dashboard: https://dashboard.stripe.com
EOF

echo "📝 Created reference file: $filename"

echo ""
echo "🎉 Production deployment preparation completed!"
echo ""
echo "📋 Next Steps:"
echo "1. ✅ Environment variables configured for production"
echo "2. ✅ Production URLs and CORS settings updated"
echo "3. ✅ STRIPE_WEBHOOK_SECRET included"
echo "4. 🚀 Trigger production deployment:"
echo "   - Option A: Vercel Dashboard > Your Project > Deployments > New Deployment"
echo "   - Option B: Push to main branch (if auto-deploy is configured)"
echo "   - Option C: vercel --prod command"
echo ""
echo "🔗 Quick Commands:"
echo "   - Deploy: vercel --prod"
echo "   - Dashboard: https://vercel.com/dashboard"
echo "   - Production URL: https://recharge-steel.vercel.app"